---
name: 'terraform'

on:
  push:
  pull_request:


jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Linter
        uses: github/super-linter@v4.9.0
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: main
...
